import 'base_material.dart';

class EquipmentMaterial extends BaseMaterial {
  // Equipment material doesn't have 'size' field
  EquipmentMaterial({
    required String name,
    required String id,
    required List<String> image,
    required int qty,
    required double length,
    required double circumference,
    required double circumference1,
    required double circumference2,
    required double zHeight,
    required double gSlantHeight,
    required double constant,
    required double totalArea,
    required String uom,
    required double diameterA3,
    required double diameterB3,
    required double diameterA2,
    required double diameterB2,
    required double diameterA1,
    required double diameterB1,
    required double circumferenceFinal,
    required double layer1Area,
    required double layer2Area,
    required double layer3Area,
    required double circumference3,
    required double circumference2Calc,
    required double circumference1Calc,
    required double o3,
    required double o2,
    required double o1,
    required String remarks,
  }) : super(
    id: id,
    name: name,
    image: image,
    qty: qty,
    length: length,
    circumference: circumference,
    circumference1: circumference1,
    circumference2: circumference2,
    zHeight: zHeight,
    gSlantHeight: gSlantHeight,
    constant: constant,
    totalArea: totalArea,
    diameterA3: diameterA3,
    diameterB3: diameterB3,
    diameterA2: diameterA2,
    diameterB2: diameterB2,
    diameterA1: diameterA1,
    diameterB1: diameterB1,
    circumferenceFinal: circumferenceFinal,
    layer1Area: layer1Area,
    layer2Area: layer2Area,
    layer3Area: layer3Area,
    circumference3: circumference3,
    circumference2Calc: circumference2Calc,
    circumference1Calc: circumference1Calc,
    o3: o3,
    o2: o2,
    o1: o1,
    remarks: remarks,
    uom: uom,
  );

  factory EquipmentMaterial.fromJson(Map<String, dynamic> json) {
    return EquipmentMaterial(
      id: json['_id'] ?? json['id'] ?? '',

      name: json['name'] ?? '',
      image: List<String>.from(json['image'] ?? []),
      qty: json['qty'] ?? 0,
      length: (json['length'] ?? 0).toDouble(),
      circumference: (json['circumference'] ?? 0).toDouble(),
      circumference1: (json['circumference_1'] ?? 0).toDouble(),
      circumference2: (json['circumference_2'] ?? 0).toDouble(),
      zHeight: (json['z_height'] ?? 0).toDouble(),
      gSlantHeight: (json['g_slant_height'] ?? 0).toDouble(),
      constant: (json['constant'] ?? 0).toDouble(),
      totalArea: (json['total_area'] ?? 0).toDouble(),
      uom: json['uom'] ?? '',
      diameterA3: (json['diameter_a3'] ?? 0).toDouble(),
      diameterB3: (json['diameter_b3'] ?? 0).toDouble(),
      diameterA2: (json['diameter_a2'] ?? 0).toDouble(),
      diameterB2: (json['diameter_b2'] ?? 0).toDouble(),
      diameterA1: (json['diameter_a1'] ?? 0).toDouble(),
      diameterB1: (json['diameter_b1'] ?? 0).toDouble(),
      circumferenceFinal: (json['circumference_final'] ?? 0).toDouble(),
      layer1Area: (json['layer_1_area'] ?? 0).toDouble(),
      layer2Area: (json['layer_2_area'] ?? 0).toDouble(),
      layer3Area: (json['layer_3_area'] ?? 0).toDouble(),
      circumference3: (json['circumference_3'] ?? 0).toDouble(),
      circumference2Calc: (json['circumference_2_calc'] ?? 0).toDouble(),
      circumference1Calc: (json['circumference_1_calc'] ?? 0).toDouble(),
      o3: (json['o3'] ?? 0).toDouble(),
      o2: (json['o2'] ?? 0).toDouble(),
      o1: (json['o1'] ?? 0).toDouble(),
      remarks: json['remarks'] ?? '',
    );
  }

  @override
  Map<String, dynamic> toJson() {
    return {'id': id,

      'name': name,
      'image': image,
      'qty': qty,
      'length': length,
      'circumference': circumference,
      'circumference_1': circumference1,
      'circumference_2': circumference2,
      'z_height': zHeight,
      'g_slant_height': gSlantHeight,
      'constant': constant,
      'total_area': totalArea,
      'uom': uom,
      'diameter_a3': diameterA3,
      'diameter_b3': diameterB3,
      'diameter_a2': diameterA2,
      'diameter_b2': diameterB2,
      'diameter_a1': diameterA1,
      'diameter_b1': diameterB1,
      'circumference_final': circumferenceFinal,
      'layer_1_area': layer1Area,
      'layer_2_area': layer2Area,
      'layer_3_area': layer3Area,
      'circumference_3': circumference3,
      'circumference_2_calc': circumference2Calc,
      'circumference_1_calc': circumference1Calc,
      'o3': o3,
      'o2': o2,
      'o1': o1,
      'remarks': remarks,
    };
  }

  @override
  EquipmentMaterial copyWith({
    String? id,
    String? name,
    List<String>? image,
    int? qty,
    double? length,
    double? circumference,
    double? circumference1,
    double? circumference2,
    double? zHeight,
    double? gSlantHeight,
    double? constant,
    double? totalArea,
    String? uom,
    double? diameterA3,
    double? diameterB3,
    double? diameterA2,
    double? diameterB2,
    double? diameterA1,
    double? diameterB1,
    double? circumferenceFinal,
    double? layer1Area,
    double? layer2Area,
    double? layer3Area,
    double? circumference3,
    double? circumference2Calc,
    double? circumference1Calc,
    double? o3,
    double? o2,
    double? o1,
    String? remarks,
  }) {
    return EquipmentMaterial(
      id: id ?? this.id,
      name: name ?? this.name,
      image: image ?? this.image,
      qty: qty ?? this.qty,
      length: length ?? this.length,
      circumference: circumference ?? this.circumference,
      circumference1: circumference1 ?? this.circumference1,
      circumference2: circumference2 ?? this.circumference2,
      zHeight: zHeight ?? this.zHeight,
      gSlantHeight: gSlantHeight ?? this.gSlantHeight,
      constant: constant ?? this.constant,
      totalArea: totalArea ?? this.totalArea,
      uom: uom ?? this.uom,
      diameterA3: diameterA3 ?? this.diameterA3,
      diameterB3: diameterB3 ?? this.diameterB3,
      diameterA2: diameterA2 ?? this.diameterA2,
      diameterB2: diameterB2 ?? this.diameterB2,
      diameterA1: diameterA1 ?? this.diameterA1,
      diameterB1: diameterB1 ?? this.diameterB1,
      circumferenceFinal: circumferenceFinal ?? this.circumferenceFinal,
      layer1Area: layer1Area ?? this.layer1Area,
      layer2Area: layer2Area ?? this.layer2Area,
      layer3Area: layer3Area ?? this.layer3Area,
      circumference3: circumference3 ?? this.circumference3,
      circumference2Calc: circumference2Calc ?? this.circumference2Calc,
      circumference1Calc: circumference1Calc ?? this.circumference1Calc,
      o3: o3 ?? this.o3,
      o2: o2 ?? this.o2,
      o1: o1 ?? this.o1,
      remarks: remarks ?? this.remarks,
    );
  }
}