import 'base_material.dart';
import 'material_setup.dart';

class EquipmentMaterial extends BaseMaterial {
  EquipmentMaterial({
    required String id,
    required String name,
    required List<String> image,
    required String uom,
    String remarks = '',
    String? materialCode,
    FieldValues? fieldValues,
    Map<String, String>? customLabels,
    int qty = 0,
    double length = 0,
    double circumference = 0,
    double circumference1 = 0,
    double circumference2 = 0,
    double zHeight = 0,
    double gSlantHeight = 0,
    double constant = 0,
    double totalArea = 0,
    double diameterA3 = 0,
    double diameterB3 = 0,
    double diameterA2 = 0,
    double diameterB2 = 0,
    double diameterA1 = 0,
    double diameterB1 = 0,
    double circumferenceFinal = 0,
    double layer1Area = 0,
    double layer2Area = 0,
    double layer3Area = 0,
    double circumference3 = 0,
    double circumference2Calc = 0,
    double circumference1Calc = 0,
    double o3 = 0,
    double o2 = 0,
    double o1 = 0,
  }) : super(
          id: id,
          name: name,
          image: image,
          uom: uom,
          remarks: remarks,
          materialCode: materialCode,
          fieldValues: fieldValues,
          customLabels: customLabels,
          qty: qty,
          length: length,
          circumference: circumference,
          circumference1: circumference1,
          circumference2: circumference2,
          zHeight: zHeight,
          gSlantHeight: gSlantHeight,
          constant: constant,
          totalArea: totalArea,
          diameterA3: diameterA3,
          diameterB3: diameterB3,
          diameterA2: diameterA2,
          diameterB2: diameterB2,
          diameterA1: diameterA1,
          diameterB1: diameterB1,
          circumferenceFinal: circumferenceFinal,
          layer1Area: layer1Area,
          layer2Area: layer2Area,
          layer3Area: layer3Area,
          circumference3: circumference3,
          circumference2Calc: circumference2Calc,
          circumference1Calc: circumference1Calc,
          o3: o3,
          o2: o2,
          o1: o1,
        );

  factory EquipmentMaterial.fromJson(Map<String, dynamic> json) {
    return EquipmentMaterial(
      id: json['_id'] ?? json['id'] ?? '',
      name: json['name'] ?? '',
      image: List<String>.from(json['image'] ?? []),
      uom: json['uom'] ?? '',
      remarks: json['remarks'] ?? '',
      materialCode: json['materialCode'] ?? json['material_code'],
      fieldValues: json['fieldValues'] != null
          ? FieldValues.fromJson(json['fieldValues'] as Map<String, dynamic>)
          : null,
      customLabels: json['custom_labels'] != null
          ? Map<String, String>.from(json['custom_labels'])
          : null,
      qty: json['qty'] ?? 0,
      length: (json['length'] ?? 0).toDouble(),
      circumference: (json['circumference'] ?? 0).toDouble(),
      circumference1: (json['circumference_1'] ?? 0).toDouble(),
      circumference2: (json['circumference_2'] ?? 0).toDouble(),
      zHeight: (json['z_height'] ?? 0).toDouble(),
      gSlantHeight: (json['g_slant_height'] ?? 0).toDouble(),
      constant: (json['constant'] ?? 0).toDouble(),
      totalArea: (json['total_area'] ?? 0).toDouble(),
      diameterA3: (json['diameter_a3'] ?? 0).toDouble(),
      diameterB3: (json['diameter_b3'] ?? 0).toDouble(),
      diameterA2: (json['diameter_a2'] ?? 0).toDouble(),
      diameterB2: (json['diameter_b2'] ?? 0).toDouble(),
      diameterA1: (json['diameter_a1'] ?? 0).toDouble(),
      diameterB1: (json['diameter_b1'] ?? 0).toDouble(),
      circumferenceFinal: (json['circumference_final'] ?? 0).toDouble(),
      layer1Area: (json['layer_1_area'] ?? 0).toDouble(),
      layer2Area: (json['layer_2_area'] ?? 0).toDouble(),
      layer3Area: (json['layer_3_area'] ?? 0).toDouble(),
      circumference3: (json['circumference_3'] ?? 0).toDouble(),
      circumference2Calc: (json['circumference_2_calc'] ?? 0).toDouble(),
      circumference1Calc: (json['circumference_1_calc'] ?? 0).toDouble(),
      o3: (json['o3'] ?? 0).toDouble(),
      o2: (json['o2'] ?? 0).toDouble(),
      o1: (json['o1'] ?? 0).toDouble(),
    );
  }

  @override
  Map<String, dynamic> toJson() {
    return {
      '_id': id,
      'name': name,
      'image': image,
      'uom': uom,
      'remarks': remarks,
      if (materialCode != null) 'materialCode': materialCode,
      if (fieldValues != null) 'fieldValues': fieldValues!.toJson(),
      if (customLabels != null) 'custom_labels': customLabels,
      'qty': qty,
      'length': length,
      'circumference': circumference,
      'circumference_1': circumference1,
      'circumference_2': circumference2,
      'z_height': zHeight,
      'g_slant_height': gSlantHeight,
      'constant': constant,
      'total_area': totalArea,
      'diameter_a3': diameterA3,
      'diameter_b3': diameterB3,
      'diameter_a2': diameterA2,
      'diameter_b2': diameterB2,
      'diameter_a1': diameterA1,
      'diameter_b1': diameterB1,
      'circumference_final': circumferenceFinal,
      'layer_1_area': layer1Area,
      'layer_2_area': layer2Area,
      'layer_3_area': layer3Area,
      'circumference_3': circumference3,
      'circumference_2_calc': circumference2Calc,
      'circumference_1_calc': circumference1Calc,
      'o3': o3,
      'o2': o2,
      'o1': o1,
    };
  }

  @override
  EquipmentMaterial copyWith({
    String? id,
    String? name,
    List<String>? image,
    String? uom,
    String? remarks,
    String? materialCode,
    FieldValues? fieldValues,
    Map<String, String>? customLabels,
    int? qty,
    double? length,
    double? circumference,
    double? circumference1,
    double? circumference2,
    double? zHeight,
    double? gSlantHeight,
    double? constant,
    double? totalArea,
    double? diameterA3,
    double? diameterB3,
    double? diameterA2,
    double? diameterB2,
    double? diameterA1,
    double? diameterB1,
    double? circumferenceFinal,
    double? layer1Area,
    double? layer2Area,
    double? layer3Area,
    double? circumference3,
    double? circumference2Calc,
    double? circumference1Calc,
    double? o3,
    double? o2,
    double? o1,
  }) {
    return EquipmentMaterial(
      id: id ?? this.id,
      name: name ?? this.name,
      image: image ?? this.image,
      uom: uom ?? this.uom,
      remarks: remarks ?? this.remarks,
      materialCode: materialCode ?? this.materialCode,
      fieldValues: fieldValues ?? this.fieldValues,
      customLabels: customLabels ?? this.customLabels,
      qty: qty ?? this.qty,
      length: length ?? this.length,
      circumference: circumference ?? this.circumference,
      circumference1: circumference1 ?? this.circumference1,
      circumference2: circumference2 ?? this.circumference2,
      zHeight: zHeight ?? this.zHeight,
      gSlantHeight: gSlantHeight ?? this.gSlantHeight,
      constant: constant ?? this.constant,
      totalArea: totalArea ?? this.totalArea,
      diameterA3: diameterA3 ?? this.diameterA3,
      diameterB3: diameterB3 ?? this.diameterB3,
      diameterA2: diameterA2 ?? this.diameterA2,
      diameterB2: diameterB2 ?? this.diameterB2,
      diameterA1: diameterA1 ?? this.diameterA1,
      diameterB1: diameterB1 ?? this.diameterB1,
      circumferenceFinal: circumferenceFinal ?? this.circumferenceFinal,
      layer1Area: layer1Area ?? this.layer1Area,
      layer2Area: layer2Area ?? this.layer2Area,
      layer3Area: layer3Area ?? this.layer3Area,
      circumference3: circumference3 ?? this.circumference3,
      circumference2Calc: circumference2Calc ?? this.circumference2Calc,
      circumference1Calc: circumference1Calc ?? this.circumference1Calc,
      o3: o3 ?? this.o3,
      o2: o2 ?? this.o2,
      o1: o1 ?? this.o1,
    );
  }
}