// lib/features/modules/all_Modules/dpr/dpr_insu/model/eqip_insu.dart

import 'base_material.dart';
import 'card_form_State.dart';
import 'field_config.dart';

class EquipmentMaterial extends BaseMaterial {
  EquipmentMaterial({
    required String id,
    required String name,
    required List<String> image,
    required String uom,
    String remarks = '',
    CardFormState? cardFormState,
    String? materialCode,
    FieldValues? fieldValues,
    Map<String, String>? customLabels,
    int displayOrder = 0,
    num qty = 0,
    double length = 0,
    double circumference = 0,
    double circumference1 = 0,
    double circumference2 = 0,
    double zHeight = 0,
    double SlantHeight = 0,
    double constant = 0,
    double totalArea = 0,
    double diameterA3 = 0,
    double diameterB3 = 0,
    double diameterA2 = 0,
    double diameterB2 = 0,
    double diameterA1 = 0,
    double diameterB1 = 0,
    double circumferenceFinal = 0,
    double layer1Area = 0,
    double layer2Area = 0,
    double layer3Area = 0,
    double circumference3 = 0,
    double circumference2Calc = 0,
    double circumference1Calc = 0,
    double o3 = 0,
    double o2 = 0,
    double o1 = 0,
  }) : super(
    id: id,
    name: name,
    image: image,
    uom: uom,
    remarks: remarks,
    displayOrder: displayOrder,
    cardFormState: cardFormState,
    materialCode: materialCode,
    fieldValues: fieldValues,
    customLabels: customLabels,
    qty: qty,
    length: length,
    circumference: circumference,
    circumference1: circumference1,
    circumference2: circumference2,
    zHeight: zHeight,
    SlantHeight: SlantHeight,
    constant: constant,
    totalArea: totalArea,
    diameterA3: diameterA3,
    diameterB3: diameterB3,
    diameterA2: diameterA2,
    diameterB2: diameterB2,
    diameterA1: diameterA1,
    diameterB1: diameterB1,
    circumferenceFinal: circumferenceFinal,
    layer1Area: layer1Area,
    layer2Area: layer2Area,
    layer3Area: layer3Area,
    circumference3: circumference3,
    circumference2Calc: circumference2Calc,
    circumference1Calc: circumference1Calc,
    o3: o3,
    o2: o2,
    o1: o1,
  );

  factory EquipmentMaterial.fromJson(Map<String, dynamic> json) {
    return EquipmentMaterial(
      id: json['_id'] as String? ?? json['id'] as String? ?? '',
      name: json['name'] as String? ?? '',
      image: List<String>.from(json['image'] as List? ?? []),
      uom: json['uom'] as String? ?? '',
      remarks: json['remarks'] as String? ?? '',
      materialCode:
      json['materialCode'] as String? ?? json['material_code'] as String?,
      cardFormState: json['cardFormState'] != null
          ? CardFormState.fromJson(
          json['cardFormState'] as Map<String, dynamic>)
          : null,
      fieldValues: json['fieldValues'] != null
          ? FieldValues.fromJson(json['fieldValues'] as Map<String, dynamic>)
          : null,
      customLabels: json['custom_labels'] != null
          ? Map<String, String>.from(json['custom_labels'] as Map)
          : null,
      qty: (json['qty'] as num?)?.toInt() ?? 0,
      length: (json['length'] as num?)?.toDouble() ?? 0,
      circumference: (json['circumference'] as num?)?.toDouble() ?? 0,
      circumference1: (json['circumference_1'] as num?)?.toDouble() ?? 0,
      circumference2: (json['circumference_2'] as num?)?.toDouble() ?? 0,
      zHeight: (json['z_height'] as num?)?.toDouble() ?? 0,
      SlantHeight: (json['slant_height'] as num?)?.toDouble() ?? 0,
      constant: (json['constant'] as num?)?.toDouble() ?? 0,
      totalArea: (json['total_area'] as num?)?.toDouble() ?? 0,
      diameterA3: (json['diameter_a3'] as num?)?.toDouble() ?? 0,
      diameterB3: (json['diameter_b3'] as num?)?.toDouble() ?? 0,
      diameterA2: (json['diameter_a2'] as num?)?.toDouble() ?? 0,
      diameterB2: (json['diameter_b2'] as num?)?.toDouble() ?? 0,
      diameterA1: (json['diameter_a1'] as num?)?.toDouble() ?? 0,
      diameterB1: (json['diameter_b1'] as num?)?.toDouble() ?? 0,
      circumferenceFinal:
      (json['circumference_final'] as num?)?.toDouble() ?? 0,
      layer1Area: (json['layer_1_area'] as num?)?.toDouble() ?? 0,
      layer2Area: (json['layer_2_area'] as num?)?.toDouble() ?? 0,
      layer3Area: (json['layer_3_area'] as num?)?.toDouble() ?? 0,
      circumference3: (json['circumference_3'] as num?)?.toDouble() ?? 0,
      circumference2Calc:
      (json['circumference_2_calc'] as num?)?.toDouble() ?? 0,
      circumference1Calc:
      (json['circumference_1_calc'] as num?)?.toDouble() ?? 0,
      o3: (json['o3'] as num?)?.toDouble() ?? 0,
      o2: (json['o2'] as num?)?.toDouble() ?? 0,
      o1: (json['o1'] as num?)?.toDouble() ?? 0,
      displayOrder: json['displayOrder'] as int? ?? 0,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    return {
      '_id': id,
      'name': name,
      'image': image,
      'uom': uom,
      'remarks': remarks,
      if (materialCode != null) 'materialCode': materialCode,
      if (cardFormState != null) 'cardFormState': cardFormState!.toJson(),
      if (fieldValues != null) 'fieldValues': fieldValues!.toJson(),
      if (customLabels != null) 'custom_labels': customLabels,
      'qty': qty,
      'length': length,
      'circumference': circumference,
      'circumference_1': circumference1,
      'circumference_2': circumference2,
      'z_height': zHeight,
      'slant_height': SlantHeight,
      'constant': constant,
      'total_area': totalArea,
      'diameter_a3': diameterA3,
      'diameter_b3': diameterB3,
      'diameter_a2': diameterA2,
      'diameter_b2': diameterB2,
      'diameter_a1': diameterA1,
      'diameter_b1': diameterB1,
      'circumference_final': circumferenceFinal,
      'layer_1_area': layer1Area,
      'layer_2_area': layer2Area,
      'layer_3_area': layer3Area,
      'circumference_3': circumference3,
      'circumference_2_calc': circumference2Calc,
      'circumference_1_calc': circumference1Calc,
      'o3': o3,
      'o2': o2,
      'o1': o1,
      'displayOrder': displayOrder,
    };
  }

  @override
  EquipmentMaterial copyWith({
    String? id,
    String? name,
    List<String>? image,
    String? uom,
    String? remarks,
    CardFormState? cardFormState,
    String? materialCode,
    FieldValues? fieldValues,
    Map<String, String>? customLabels,
    num? qty,
    double? length,
    double? circumference,
    double? circumference1,
    double? circumference2,
    double? zHeight,
    double? SlantHeight,
    double? constant,
    double? totalArea,
    double? diameterA3,
    double? diameterB3,
    double? diameterA2,
    double? diameterB2,
    double? diameterA1,
    double? diameterB1,
    double? circumferenceFinal,
    double? layer1Area,
    double? layer2Area,
    double? layer3Area,
    double? circumference3,
    double? circumference2Calc,
    double? circumference1Calc,
    double? o3,
    double? o2,
    double? o1,
    int? displayOrder,
  }) {
    return EquipmentMaterial(
      id: id ?? this.id,
      name: name ?? this.name,
      image: image ?? this.image,
      uom: uom ?? this.uom,
      remarks: remarks ?? this.remarks,
      cardFormState: cardFormState ?? this.cardFormState,
      materialCode: materialCode ?? this.materialCode,
      fieldValues: fieldValues ?? this.fieldValues,
      customLabels: customLabels ?? this.customLabels,
      qty: qty ?? this.qty,
      length: length ?? this.length,
      circumference: circumference ?? this.circumference,
      circumference1: circumference1 ?? this.circumference1,
      circumference2: circumference2 ?? this.circumference2,
      zHeight: zHeight ?? this.zHeight,
      SlantHeight: SlantHeight ?? this.SlantHeight,
      constant: constant ?? this.constant,
      totalArea: totalArea ?? this.totalArea,
      diameterA3: diameterA3 ?? this.diameterA3,
      diameterB3: diameterB3 ?? this.diameterB3,
      diameterA2: diameterA2 ?? this.diameterA2,
      diameterB2: diameterB2 ?? this.diameterB2,
      diameterA1: diameterA1 ?? this.diameterA1,
      diameterB1: diameterB1 ?? this.diameterB1,
      circumferenceFinal: circumferenceFinal ?? this.circumferenceFinal,
      layer1Area: layer1Area ?? this.layer1Area,
      layer2Area: layer2Area ?? this.layer2Area,
      layer3Area: layer3Area ?? this.layer3Area,
      circumference3: circumference3 ?? this.circumference3,
      circumference2Calc: circumference2Calc ?? this.circumference2Calc,
      circumference1Calc: circumference1Calc ?? this.circumference1Calc,
      o3: o3 ?? this.o3,
      o2: o2 ?? this.o2,
      o1: o1 ?? this.o1,
      displayOrder: displayOrder ?? this.displayOrder,
    );
  }
}